from langgraph.graph import StateGraph, END

from state.triage_state import TriageState

from agents.session_agent import session_agent
from agents.conversation_agent import conversation_agent
from agents.general_conversation_agent import general_conversation_agent
from agents.symptom_agent import symptom_agent
from agents.planner_agent import planner_agent
from agents.risk_agent import risk_agent
from agents.supervisor_agent import supervisor_agent
from agents.persistence_agent import persistence_agent
from application.config.llm_config import LLMConfig
from infrastructure.llm.llm_factory import create_llm

from agents.general_conversation_agent import general_conversation_agent
# =============================================================
# Intent Router
# =============================================================

def route_intent(state):
    """
    Route the conversation to either:

    - TRIAGE flow
    - GENERAL conversation

    Active triage always has priority over GENERAL.
    """

    intent = state.get("intent")

    # ---------------------------------------------------------
    # Active triage
    # ---------------------------------------------------------

    if (
        state.get("symptoms")
        and (
            state.get("missing_information")
            or state.get("next_question") is not None
        )
    ):
        return "triage"

    # ---------------------------------------------------------
    # Explicit intent
    # ---------------------------------------------------------

    if intent == "TRIAGE":
        return "triage"

    if intent == "GENERAL":
        return "general"

    # ---------------------------------------------------------
    # Backward compatibility
    # ---------------------------------------------------------

    if state.get("symptoms"):
        return "triage"

    if state.get("age") is not None:
        return "triage"

    if state.get("duration") is not None:
        return "triage"

    if state.get("severity") is not None:
        return "triage"

    if state.get("next_question") is not None:
        return "triage"

    # ---------------------------------------------------------
    # Default
    # ---------------------------------------------------------

    return "general"


# =============================================================
# Planner Router
# =============================================================

def route_planner(state):
    """
    Decide whether the workflow should:

    - perform risk assessment
    - wait for more information
    """

    symptoms = state.get("symptoms") or []
    severity = state.get("severity")

    # ---------------------------------------------------------
    # Immediate high-risk conditions
    # ---------------------------------------------------------

    if (
        "chest pain" in symptoms
        and "shortness of breath" in symptoms
    ):
        return "risk"

    if severity == "severe":
        return "risk"

    # ---------------------------------------------------------
    # Missing information
    # ---------------------------------------------------------

    missing_information = (
        state.get("missing_information") or []
    )

    if missing_information:
        return "ask"

    # ---------------------------------------------------------
    # Complete information
    # ---------------------------------------------------------

    return "risk"


# =============================================================
# Risk Debug Node
# =============================================================

def debug_risk_state(state):
    """
    Temporary debugging node.

    Can be removed later after the LLM/risk pipeline
    becomes stable.
    """

    print("\n========== AFTER RISK AGENT ==========")

    print(
        "risk_level:",
        state.get("risk_level"),
    )

    print(
        "confidence:",
        state.get("confidence"),
    )

    print(
        "red_flags:",
        state.get("red_flags"),
    )

    print(
        "recommendation:",
        state.get("recommendation"),
    )

    print("\n--- LLM RESULT ---")

    print(
        "llm_risk_level:",
        state.get("llm_risk_level"),
    )

    print(
        "llm_confidence:",
        state.get("llm_confidence"),
    )

    print(
        "llm_red_flags:",
        state.get("llm_red_flags"),
    )

    print(
        "llm_recommendation:",
        state.get("llm_recommendation"),
    )

    print("=======================================\n")

    return state


# =============================================================
# General Conversation Node
# =============================================================

def general_conversation(state):
    """
    Final processing node for GENERAL conversations.

    The actual LLM response is generated by
    general_conversation_agent.
    """

    response = state.get("assistant_response")

    if response is None:
        response = state.get("response")

    if response is None:
        response = (
            "Hello. How can I help you?"
        )

    return {
        **state,
        "assistant_response": response,
        "response": response,
    }


# =============================================================
# Build Graph
# =============================================================

def build_triage_graph(llm_service=None):
    
    graph = StateGraph(TriageState)

    # =========================================================
    # Nodes
    # =========================================================

    # ---------------------------------------------------------
    # Session
    # ---------------------------------------------------------

    graph.add_node(
        "session",
        session_agent,
    )

    # ---------------------------------------------------------
    # Conversation / Intent Detection
    # ---------------------------------------------------------

    graph.add_node(
        "conversation",
        lambda state: conversation_agent(
            state,
            llm_service=llm_service,
        ),
    )

    # ---------------------------------------------------------
    # General Conversation
    # ---------------------------------------------------------

    graph.add_node(
        "general_conversation",
        lambda state: general_conversation_agent(
            state,
            llm_service=llm_service,
        ),
    )

    # ---------------------------------------------------------
    # Symptom Analysis
    # ---------------------------------------------------------

    graph.add_node(
        "symptom_analysis",
        symptom_agent,
    )

    # ---------------------------------------------------------
    # Planner
    # ---------------------------------------------------------

    graph.add_node(
        "planner",
        planner_agent,
    )

    # ---------------------------------------------------------
    # Risk Assessment
    # ---------------------------------------------------------

    graph.add_node(
        "risk_assessment",
        lambda state: risk_agent(
            state,
            llm_service=llm_service,
        ),
    )

    # ---------------------------------------------------------
    # Debug
    # ---------------------------------------------------------

    graph.add_node(
        "debug_risk",
        debug_risk_state,
    )

    # ---------------------------------------------------------
    # Supervisor
    # ---------------------------------------------------------

    graph.add_node(
        "supervisor",
        supervisor_agent,
    )

    # ---------------------------------------------------------
    # Persistence
    # ---------------------------------------------------------

    graph.add_node(
        "persistence",
        persistence_agent,
    )

    # =========================================================
    # Entry Point
    # =========================================================

    graph.set_entry_point(
        "session"
    )

    # =========================================================
    # Session -> Conversation
    # =========================================================

    graph.add_edge(
        "session",
        "conversation",
    )

    # =========================================================
    # Conversation -> Intent Router
    # =========================================================

    graph.add_conditional_edges(
        "conversation",
        route_intent,
        {
            "triage": "symptom_analysis",
            "general": "general_conversation",
        },
    )

    # =========================================================
    # GENERAL -> END
    # =========================================================

    graph.add_edge(
        "general_conversation",
        END,
    )

    # =========================================================
    # TRIAGE
    # =========================================================

    graph.add_edge(
        "symptom_analysis",
        "planner",
    )

    # =========================================================
    # Planner -> Risk / Ask
    # =========================================================

    graph.add_conditional_edges(
        "planner",
        route_planner,
        {
            "risk": "risk_assessment",
            "ask": END,
        },
    )

    # =========================================================
    # Risk -> Debug
    # =========================================================

    graph.add_edge(
        "risk_assessment",
        "debug_risk",
    )

    # =========================================================
    # Debug -> Supervisor
    # =========================================================

    graph.add_edge(
        "debug_risk",
        "supervisor",
    )

    # =========================================================
    # Supervisor -> Persistence
    # =========================================================

    graph.add_edge(
        "supervisor",
        "persistence",
    )

    # =========================================================
    # Persistence -> END
    # =========================================================

    graph.add_edge(
        "persistence",
        END,
    )

    # =========================================================
    # Compile
    # =========================================================

    return graph.compile()


# =============================================================
# LLM Configuration
# =============================================================

llm_config = LLMConfig(
    provider="ollama",
    model="gemma3",
)


# =============================================================
# LLM Service
# =============================================================

llm_service = create_llm(
    llm_config,
)


# =============================================================
# Global Graph
# =============================================================

triage_graph = build_triage_graph(
    llm_service=llm_service,
)